# Generated by Django 3.2.9 on 2022-01-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('recruits', '0001_initial'),
        ('companies', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postresume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='users.userinfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyinfo', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.areas', verbose_name='办公地点'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='node_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_1_related', to='recruits.posttree', verbose_name='一级岗位'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='node_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_2_related', to='recruits.posttree', verbose_name='二级岗位'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='node_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_3_related', to='recruits.posttree', verbose_name='三级岗位'),
        ),
    ]
