# Generated by Django 3.2.9 on 2022-01-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0002_auto_20211128_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinfo',
            name='salary_type',
        ),
    ]
