# Generated by Django 3.2.9 on 2022-01-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220113_1834'),
        ('recruits', '0004_postresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresume',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='recruits.postinfo', verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='postresume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='users.userinfo', verbose_name='用户'),
        ),
    ]
