# Generated by Django 3.2.9 on 2022-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='总分'),
        ),
    ]
