# Generated by Django 3.2.9 on 2022-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examquestion_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='total_score',
        ),
        migrations.AddField(
            model_name='exam',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='score',
            field=models.IntegerField(default=0, verbose_name='每题分数'),
        ),
    ]
