# Generated by Django 3.2.9 on 2022-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20220313_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='answer',
            field=models.ManyToManyField(to='exams.QuestionChoice', verbose_name='用户答案'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='是否需要选择'),
        ),
    ]
