# Generated by Django 3.2.9 on 2022-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20220313_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='answer',
            field=models.ManyToManyField(blank=True, to='exams.QuestionChoice', verbose_name='用户答案'),
        ),
    ]
