# Generated by Django 3.2.9 on 2022-03-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_examquestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='score',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='full_score',
            field=models.IntegerField(default=0, verbose_name='每题总分数'),
        ),
    ]
