# Generated by Django 3.2.9 on 2022-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20220313_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='score',
            field=models.IntegerField(default=0, verbose_name='该题得分'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='full_score',
            field=models.IntegerField(default=0, verbose_name='该题总分'),
        ),
    ]
