# Generated by Django 3.2.9 on 2021-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('province', models.TextField(default='', verbose_name='省份')),
                ('city', models.TextField(default='', verbose_name='城市')),
                ('session_key', models.TextField(default='')),
                ('avatar', models.ImageField(default='', upload_to='avatar', verbose_name='头像')),
                ('openid', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=16, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='性别')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('location', models.CharField(default='', max_length=200, verbose_name='居住地')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('email', models.CharField(default='', max_length=100, verbose_name='邮箱')),
                ('work_experience', models.TextField(default='', verbose_name='工作经历')),
                ('school', models.TextField(default='', verbose_name='学校')),
                ('qualification', models.IntegerField(choices=[(0, '未知'), (1, '不限'), (2, '小学'), (3, '初中'), (4, '高中'), (5, '中专'), (6, '大专'), (7, '本科'), (8, '硕士'), (9, '博士')], default=0, verbose_name='学历')),
                ('major', models.CharField(default='', max_length=100, verbose_name='专业')),
                ('is_graduate', models.BooleanField(default=False, verbose_name='应届生')),
                ('edu_details', models.TextField(default='', verbose_name='教育经历详情')),
                ('skills', models.TextField(default='', verbose_name='技能')),
                ('training_experience', models.TextField(default='', verbose_name='培训经历')),
                ('personal_experience', models.TextField(default='', verbose_name='个人经历')),
                ('self_evaluate', models.TextField(default='', verbose_name='自我评价')),
                ('intention', models.ManyToManyField(blank=True, default=None, to='recruits.PostTree', verbose_name='求职意向')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'tb_user_info',
            },
        ),
    ]
