# Generated by Django 3.2.9 on 2022-01-13 12:15

import albatross.utils.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruits', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('avatar', models.ImageField(default='avatar/default.jpg', storage=albatross.utils.storage.AvatarStorage, upload_to='avatar', verbose_name='头像')),
                ('openid', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=16, verbose_name='姓名')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('sex', models.SmallIntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='性别')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('email', models.CharField(default='', max_length=100, verbose_name='邮箱')),
                ('school', models.TextField(default='', verbose_name='学校')),
                ('major', models.CharField(default='', max_length=100, verbose_name='专业')),
                ('qualification', models.IntegerField(choices=[(0, '未知'), (1, '不限'), (2, '小学'), (3, '初中'), (4, '高中'), (5, '中专'), (6, '大专'), (7, '本科'), (8, '硕士'), (9, '博士')], default=0, verbose_name='学历')),
                ('is_graduate', models.BooleanField(default=False, verbose_name='应届生')),
                ('edu_details', models.TextField(default='', verbose_name='教育经历详情')),
                ('work_experience', models.TextField(default='', verbose_name='工作经历')),
                ('skills', models.TextField(default='', verbose_name='技能')),
                ('training_experience', models.TextField(default='', verbose_name='培训经历')),
                ('personal_experience', models.TextField(default='', verbose_name='个人经历')),
                ('self_evaluate', models.TextField(default='', verbose_name='自我评价')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='areas.areas', verbose_name='城市')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='areas.areas', verbose_name='居住地')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='areas.areas', verbose_name='省份')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'tb_user_info',
            },
        ),
        migrations.CreateModel(
            name='UserIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0, verbose_name='薪资')),
                ('language', models.CharField(default='', max_length=100, verbose_name='语言')),
                ('platform', models.CharField(default='', max_length=100, verbose_name='平台')),
                ('working_type', models.CharField(default='', max_length=100, verbose_name='工作类型')),
                ('area', models.CharField(default='', max_length=100, verbose_name='地区')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.areas', verbose_name='城市')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.posttree', verbose_name='岗位分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intention', to='users.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户意向',
                'verbose_name_plural': '用户意向',
                'db_table': 'tb_user_intention',
            },
        ),
    ]
