# Generated by Django 3.2.9 on 2022-01-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0003_remove_postinfo_salary_type'),
        ('areas', '0002_areas_display'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='intention',
        ),
        migrations.CreateModel(
            name='UserIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0, verbose_name='薪资')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areas', verbose_name='城市')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.posttree', verbose_name='岗位分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户意向',
                'verbose_name_plural': '用户意向',
                'db_table': 'tb_user_intention',
            },
        ),
    ]
