# Generated by Django 3.2.9 on 2022-01-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220113_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintention',
            name='area',
            field=models.CharField(default='', max_length=100, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='userintention',
            name='language',
            field=models.CharField(default='', max_length=100, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='userintention',
            name='platform',
            field=models.CharField(default='', max_length=100, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='userintention',
            name='working_type',
            field=models.CharField(default='', max_length=100, verbose_name='工作类型'),
        ),
        migrations.AlterField(
            model_name='userintention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intention', to='users.userinfo', verbose_name='用户'),
        ),
    ]
