# Generated by Django 3.2.9 on 2022-01-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_areas_display'),
        ('users', '0003_auto_20220113_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintention',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.areas', verbose_name='城市'),
        ),
    ]
