# Generated by Django 3.2.9 on 2021-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='公司名称')),
                ('info', models.TextField(default='', verbose_name='公司详细信息')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'db_table': 'tb_company_info',
            },
        ),
    ]
