# Generated by Django 3.2.9 on 2021-11-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(default='')),
                ('company_info', models.TextField(default='')),
            ],
        ),
    ]
