# Generated by Django 3.2.9 on 2021-11-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='岗位分类名')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recruit.posttree', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '岗位树状分类',
            },
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='岗位ID')),
                ('post_name', models.CharField(default='', max_length=100, verbose_name='岗位名称')),
                ('salary_low', models.IntegerField(default=0, verbose_name='薪资下限')),
                ('salary_high', models.IntegerField(default=0, verbose_name='薪资上限')),
                ('salary_type', models.BooleanField(blank=True, null=True, verbose_name='薪资类型')),
                ('education', models.IntegerField(choices=[(-1, '未知'), (0, '不限'), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士')], default=0, verbose_name='学历要求')),
                ('experience', models.CharField(default='', max_length=100, verbose_name='工作经验')),
                ('description', models.TextField(default='', verbose_name='岗位介绍')),
                ('welfare', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo', verbose_name='公司')),
                ('node_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_1_related', to='recruit.posttree', verbose_name='一级岗位')),
                ('node_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_2_related', to='recruit.posttree', verbose_name='二级岗位')),
                ('node_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_3_related', to='recruit.posttree', verbose_name='三级岗位')),
            ],
            options={
                'verbose_name': '岗位信息',
            },
        ),
    ]
