# Generated by Django 3.2.9 on 2021-11-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('recruit', '0002_alter_postinfo_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='score',
            field=models.IntegerField(default=0, verbose_name='岗位评分'),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.areas', verbose_name='办公地点'),
        ),
    ]
