# Generated by Django 3.2.9 on 2021-11-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20211123_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttree',
            name='type',
            field=models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], default=1, verbose_name='岗位分类类型'),
            preserve_default=False,
        ),
    ]
