# Generated by Django 3.2.9 on 2021-11-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_alter_postinfo_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinfo',
            name='salary_type',
            field=models.IntegerField(choices=[(0, '未知'), (1, '月薪'), (2, '年薪')], default=0, verbose_name='薪资类型'),
        ),
    ]
