# Generated by Django 3.1.7 on 2021-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('session_key', models.TextField(default='')),
                ('avatar', models.TextField(default='')),
                ('openid', models.TextField(default='')),
            ],
        ),
    ]
