# Generated by Django 3.1.7 on 2021-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='educational_experience',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='language_ability',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='opration_experience',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='personal_works',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='edu_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_graduate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='personal_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='qualification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='self_evaluate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='training_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='work_experience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.TextField(default=''),
        ),
    ]
