# Generated by Django 3.1.7 on 2021-07-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_father', models.TextField(default='')),
                ('name_son', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='post_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='cid',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='company_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='node_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='node_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='node_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='requirement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='welfare',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='educational_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='language_ability',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='opration_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='personal_works',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
