# Generated by Django 3.2.9 on 2021-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('session_key', models.TextField(default='')),
                ('avatar', models.TextField(default='')),
                ('openid', models.TextField(default='')),
                ('name', models.CharField(max_length=16)),
                ('sex', models.IntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0)),
                ('birth', models.DateField(blank=True, null=True)),
                ('location', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=100)),
                ('work_experience', models.TextField(default='')),
                ('school', models.TextField(default='')),
                ('qualification', models.TextField(default='')),
                ('major', models.CharField(default='', max_length=100)),
                ('is_graduate', models.BooleanField()),
                ('edu_details', models.TextField(default='')),
                ('skills', models.TextField(default='')),
                ('training_experience', models.TextField(default='')),
                ('personal_experience', models.TextField(default='')),
                ('self_evaluate', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
