# Generated by Django 3.2.9 on 2021-11-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default='')),
                ('node_3', models.TextField(default='')),
            ],
            options={
                'verbose_name': '用户意向',
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.TextField(default='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.TextField(default='', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='edu_details',
            field=models.TextField(default='', verbose_name='教育经历详情'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_graduate',
            field=models.BooleanField(default=False, verbose_name='应届生'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.TextField(default='', verbose_name='居住地'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='major',
            field=models.CharField(default='', max_length=100, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=16, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='personal_experience',
            field=models.TextField(default='', verbose_name='个人经历'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='province',
            field=models.TextField(default='', verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qualification',
            field=models.IntegerField(choices=[(-1, '未知'), (0, '不限'), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士')], default=-1, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.TextField(default='', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='self_evaluate',
            field=models.TextField(default='', verbose_name='自我评价'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skills',
            field=models.TextField(default='', verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='training_experience',
            field=models.TextField(default='', verbose_name='培训经历'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work_experience',
            field=models.TextField(default='', verbose_name='工作经历'),
        ),
    ]
