# Generated by Django 3.2.9 on 2021-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211122_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='qualification',
            field=models.IntegerField(choices=[(0, '未知'), (1, '不限'), (2, '小学'), (3, '初中'), (4, '高中'), (5, '中专'), (6, '大专'), (7, '本科'), (8, '硕士'), (9, '博士')], default=0, verbose_name='学历'),
        ),
    ]
