# Generated by Django 3.2.9 on 2021-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userinfo_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='居住地'),
        ),
    ]
