# Generated by Django 3.2.9 on 2021-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20211122_1809'),
        ('user', '0004_alter_userinfo_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intention',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='intention',
            field=models.ManyToManyField(to='recruit.PostTree', verbose_name='求职意向'),
        ),
    ]
