# Generated by Django 3.2.9 on 2021-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20211122_1809'),
        ('user', '0005_auto_20211122_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='intention',
            field=models.ManyToManyField(blank=True, default=None, to='recruit.PostTree', verbose_name='求职意向'),
        ),
    ]
